export const homePage = 'Home'
export const signUp = 'SignUp/*'
export const joinOurTeam = 'JoinOurTeam'
export const book = 'Book'
export const registration = 'registration'

export const regularlyPage = 'regularly'
export const deepPage = 'deep'
export const officePage = 'office'
export const windowsPage = 'windows'